import type { TemplateManifest } from "@/lib/template-manifest";

export type TemplateFamilyId =
  | "warm-professional"
  | "calm-academic"
  | "modern-clean"
  | "highlight-forward";

export type CuratedTemplateManifest = Omit<
  TemplateManifest,
  "familyId" | "familyLabel" | "fitSummary" | "previewHighlights"
> & {
  familyId: TemplateFamilyId;
  familyLabel: string;
  fitSummary: string;
  previewHighlights: string[];
};

export const TEMPLATE_FAMILY_ORDER: TemplateFamilyId[] = [
  "warm-professional",
  "calm-academic",
  "modern-clean",
  "highlight-forward",
];

export const TEMPLATE_FAMILY_LIBRARY: CuratedTemplateManifest[] = [
  {
    version: "v1",
    templateId: "flagship-reference",
    name: "Flagship Reference",
    displayName: "稳妥简洁",
    description: "信息排布最稳，适合大多数校招简历。",
    familyId: "warm-professional",
    familyLabel: "温和专业",
    fitSummary: "适合想先交出一版稳妥、可信、不过度冒险的校招简历。",
    previewHighlights: ["抬头信息完整清楚", "教育与经历层次稳定", "整体观感正式克制"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "navy",
      dividerStyle: "line",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "name-left-photo-right" },
      education: { variant: "highlight-strip" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "two-column-table" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "airy",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "warm-storyteller",
    name: "Warm Storyteller",
    displayName: "温润叙事",
    description: "更强调经历展开与阅读节奏，适合内容扎实的申请者。",
    familyId: "warm-professional",
    familyLabel: "温和专业",
    fitSummary: "适合经历条目比较完整，想让招聘方顺着叙事读下去的简历。",
    previewHighlights: ["标题区保留正式感", "经历条目更偏展开阅读", "整页留白偏舒展"],
    tone: "calm",
    page: {
      size: "A4",
      marginPreset: "airy",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "burgundy",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "experience", "skills", "awards"],
    sections: {
      hero: { variant: "name-left-photo-right" },
      education: { variant: "highlight-strip" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "airy",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "burgundy-brief",
    name: "Burgundy Brief",
    displayName: "稳重提炼",
    description: "在正式感里增加一点重点提示，适合经历较多但不想太锋利。",
    familyId: "warm-professional",
    familyLabel: "温和专业",
    fitSummary: "适合需要压缩信息量，但仍想保持成熟、稳重观感的简历。",
    previewHighlights: ["酒红强调色更显成熟", "信息压缩但不拥挤", "技能与奖项更利于扫读"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "burgundy",
      dividerStyle: "line",
    },
    sectionOrder: ["experience", "education", "skills", "awards"],
    sections: {
      hero: { variant: "name-left-photo-right" },
      education: { variant: "compact-rows" },
      experience: { variant: "metric-first" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["skills", "awards", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "ivory-scholar",
    name: "Ivory Scholar",
    displayName: "学术清朗",
    description: "更强调教育与学术线索，适合科研、学术或研究型申请。",
    familyId: "calm-academic",
    familyLabel: "沉静学院",
    fitSummary: "适合教育背景、课程项目、研究经历较强，需要先建立学术可信度的简历。",
    previewHighlights: ["教育模块识别度更高", "学院气质更明显", "内容节奏偏平稳理性"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "airy",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "ink",
      dividerStyle: "line",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "highlight-strip" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "two-column-table" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "airy",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "balanced-ledger",
    name: "Balanced Ledger",
    displayName: "理性平衡",
    description: "教育、经历、技能分配更均衡，适合综合型校招简历。",
    familyId: "calm-academic",
    familyLabel: "沉静学院",
    fitSummary: "适合没有单一超强亮点，但整体履历比较平均、需要显得清楚可靠的简历。",
    previewHighlights: ["阅读路径均衡稳定", "正文块与信息块比例克制", "适合保守投递场景"],
    tone: "calm",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "navy",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "experience", "skills", "awards"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "compact-rows" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "quiet-focus",
    name: "Quiet Focus",
    displayName: "低噪聚焦",
    description: "减少视觉噪音，把读者注意力留在教育与成果本身。",
    familyId: "calm-academic",
    familyLabel: "沉静学院",
    fitSummary: "适合内容本身已经够强，不希望版式抢戏的简历。",
    previewHighlights: ["抬头更轻更克制", "内容分组清爽低噪", "整体气质偏研究型"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "ink",
      dividerStyle: "line",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "highlight-strip" },
      experience: { variant: "metric-first" },
      awards: { variant: "inline-list" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["experience", "awards", "skills"],
    },
  },
  {
    version: "v1",
    templateId: "compact-elegance",
    name: "Compact Elegance",
    displayName: "紧凑清晰",
    description: "内容更紧凑，适合信息稍多的一页简历。",
    familyId: "modern-clean",
    familyLabel: "现代简洁",
    fitSummary: "适合经历和技能较多，需要在一页里压紧信息密度的简历。",
    previewHighlights: ["版面利用率更高", "技能与经历压缩明确", "适合一页内塞入更多事实"],
    tone: "modern",
    page: {
      size: "A4",
      marginPreset: "tight",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "forest",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "compact-rows" },
      experience: { variant: "compact-cards" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "tight",
      overflowPriority: ["skills", "awards", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "fresh-grid",
    name: "Fresh Grid",
    displayName: "清新网格",
    description: "模块边界更清楚，适合信息项多、需要快速扫读的简历。",
    familyId: "modern-clean",
    familyLabel: "现代简洁",
    fitSummary: "适合项目、技能、奖项都不少，想让 HR 很快完成第一轮浏览的简历。",
    previewHighlights: ["模块切分更鲜明", "扫读路径更直接", "信息点多时更不易乱"],
    tone: "modern",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "navy",
      dividerStyle: "soft",
    },
    sectionOrder: ["experience", "education", "skills", "awards"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "compact-rows" },
      experience: { variant: "compact-cards" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["skills", "experience", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "slate-minimal",
    name: "Slate Minimal",
    displayName: "轻简清楚",
    description: "结构更轻，适合先快速看清关键信息。",
    familyId: "modern-clean",
    familyLabel: "现代简洁",
    fitSummary: "适合想降低装饰感、把姓名、教育、经历核心事实直接交给读者的简历。",
    previewHighlights: ["抬头极简", "视觉噪音更少", "整体感受更轻更快"],
    tone: "calm",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "ink",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "experience", "skills", "awards"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "compact-rows" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "forest-structured",
    name: "Forest Structured",
    displayName: "结构利落",
    description: "强调模块秩序和小标题识别，适合偏运营、产品、通用职能岗位。",
    familyId: "modern-clean",
    familyLabel: "现代简洁",
    fitSummary: "适合想让信息显得有条理、判断成本低的职能型或综合型简历。",
    previewHighlights: ["模块秩序更强", "标题识别明显", "版式显得清洁不呆板"],
    tone: "modern",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "forest",
      dividerStyle: "line",
    },
    sectionOrder: ["experience", "education", "awards", "skills"],
    sections: {
      hero: { variant: "name-left-photo-right" },
      education: { variant: "compact-rows" },
      experience: { variant: "compact-cards" },
      awards: { variant: "two-column-table" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["experience", "skills", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "classic-banner",
    name: "Classic Banner",
    displayName: "重点突出",
    description: "标题更醒目，适合把亮点放在上半页。",
    familyId: "highlight-forward",
    familyLabel: "亮点前置",
    fitSummary: "适合已经有明确成果点，想把亮点和结果尽快抬到读者眼前的简历。",
    previewHighlights: ["顶部识别更强", "结果导向感更明显", "适合抢前几秒注意力"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "burgundy",
      dividerStyle: "bar",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "classic-banner" },
      education: { variant: "highlight-strip" },
      experience: { variant: "metric-first" },
      awards: { variant: "two-column-table" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["experience", "awards", "skills"],
    },
  },
  {
    version: "v1",
    templateId: "metric-pulse",
    name: "Metric Pulse",
    displayName: "结果先行",
    description: "更强调量化结果和指标，适合数据、增长、运营、商业分析方向。",
    familyId: "highlight-forward",
    familyLabel: "亮点前置",
    fitSummary: "适合有数字结果、增长指标、项目成效，想优先放大成果的简历。",
    previewHighlights: ["经历更突出数字结果", "阅读重点更靠前", "适合结果导向岗位"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "tight",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "forest",
      dividerStyle: "bar",
    },
    sectionOrder: ["experience", "education", "skills", "awards"],
    sections: {
      hero: { variant: "classic-banner" },
      education: { variant: "compact-rows" },
      experience: { variant: "metric-first" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "tight",
      overflowPriority: ["experience", "skills", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "spotlight-skills",
    name: "Spotlight Skills",
    displayName: "技能抢眼",
    description: "强化技能与标签区，适合技能面要求明确的岗位。",
    familyId: "highlight-forward",
    familyLabel: "亮点前置",
    fitSummary: "适合前端、设计、算法、数据等技能筛选明显的岗位投递。",
    previewHighlights: ["技能模块更易扫读", "标签感更强", "适合有明确工具栈的人选"],
    tone: "modern",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "navy",
      dividerStyle: "bar",
    },
    sectionOrder: ["skills", "experience", "education", "awards"],
    sections: {
      hero: { variant: "classic-banner" },
      education: { variant: "compact-rows" },
      experience: { variant: "compact-cards" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["skills", "experience", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "results-first",
    name: "Results First",
    displayName: "亮点直给",
    description: "压缩叙事，尽快把最强卖点抬到前面，适合快节奏筛选。",
    familyId: "highlight-forward",
    familyLabel: "亮点前置",
    fitSummary: "适合投递量大、筛选快、希望简历在几秒内就传达价值的场景。",
    previewHighlights: ["信息起手更直接", "重点露出速度更快", "适合快筛岗位场景"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "tight",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "burgundy",
      dividerStyle: "bar",
    },
    sectionOrder: ["experience", "skills", "education", "awards"],
    sections: {
      hero: { variant: "classic-banner" },
      education: { variant: "compact-rows" },
      experience: { variant: "metric-first" },
      awards: { variant: "inline-list" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "tight",
      overflowPriority: ["experience", "skills", "awards"],
    },
  },
];
