import type { CuratedTemplateManifest, TemplateFamilyId } from "@/lib/template-types";

export const TEMPLATE_FAMILY_LABELS: Record<TemplateFamilyId, string> = {
  "warm-professional": "温暖专业",
  "calm-academic": "冷静学术",
  "modern-clean": "现代清爽",
  "highlight-forward": "重点鲜明",
};

export const TEMPLATE_FAMILY_SUMMARIES: Record<TemplateFamilyId, string> = {
  "warm-professional": "适合想先投出一版稳妥、正式、不过分冒险的校招简历。",
  "calm-academic": "适合教育亮点、研究经历或学术信号更强，想把履历讲得更清楚的人。",
  "modern-clean": "适合想显得轻一点、利落一点，但又不想做得太花的人。",
  "highlight-forward": "适合成绩、奖项或结果数字很明确，想先把亮点抬出来的人。",
};

export const TEMPLATE_FAMILY_ORDER: TemplateFamilyId[] = [
  "warm-professional",
  "calm-academic",
  "modern-clean",
  "highlight-forward",
];

const TEMPLATE_FAMILY_LIBRARY_DEFINITIONS: CuratedTemplateManifest[] = [
  {
    version: "v1",
    templateId: "flagship-reference",
    name: "Flagship Reference",
    displayName: "稳妥通用版",
    description: "先把姓名、教育和经历都讲清楚，适合大多数校招简历。",
    familyId: "warm-professional",
    familyLabel: TEMPLATE_FAMILY_LABELS["warm-professional"],
    bestFor: "适合先稳稳投递",
    fitSummary: "适合想先交出一版稳妥、可信、不过度冒险的校招简历。",
    previewHighlights: ["抬头信息完整清楚", "教育与经历层次稳定", "整体观感正式克制"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "navy",
      dividerStyle: "line",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "name-left-photo-right" },
      education: { variant: "highlight-strip" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "two-column-table" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "airy",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "warm-education-first",
    name: "Warm Education First",
    displayName: "教育亮点先读",
    description: "先看学校、专业和学业亮点，适合先建立可信度。",
    familyId: "warm-professional",
    familyLabel: TEMPLATE_FAMILY_LABELS["warm-professional"],
    bestFor: "适合教育亮点强",
    fitSummary: "适合院校背景、成绩、保研或课程表现比较强，想先把教育信号讲清楚的人。",
    previewHighlights: ["教育前置", "学校信息更醒目", "阅读节奏温和稳定"],
    tone: "calm",
    page: {
      size: "A4",
      marginPreset: "airy",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "burgundy",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "experience", "skills", "awards"],
    sections: {
      hero: { variant: "split-meta-band" },
      education: { variant: "school-emphasis" },
      experience: { variant: "role-first" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "airy",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "warm-experience-first",
    name: "Warm Experience First",
    displayName: "经历结果先读",
    description: "先看实习、项目和结果，适合已经有成型经历的人。",
    familyId: "warm-professional",
    familyLabel: TEMPLATE_FAMILY_LABELS["warm-professional"],
    bestFor: "适合经历已经成型",
    fitSummary: "适合有完整实习、项目或校园经历，想先展示做过什么和做成什么的人。",
    previewHighlights: ["经历前置", "页头更直接清楚", "结果摘要更靠前"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "burgundy",
      dividerStyle: "line",
    },
    sectionOrder: ["experience", "education", "skills", "awards"],
    sections: {
      hero: { variant: "name-left-photo-right" },
      education: { variant: "compact-rows" },
      experience: { variant: "result-callout" },
      awards: { variant: "pill-row" },
      skills: { variant: "label-columns" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["skills", "awards", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "warm-profile-card",
    name: "Warm Profile Card",
    displayName: "抬头信息强化",
    description: "先把个人信息收成更完整的抬头区，适合想让第一页更稳的人。",
    familyId: "warm-professional",
    familyLabel: TEMPLATE_FAMILY_LABELS["warm-professional"],
    bestFor: "适合抬头信息较全",
    fitSummary: "适合希望把个人信息、联系方式和基础画像收成一个稳定头部卡片的人。",
    previewHighlights: ["顶部档案卡更完整", "抬头结构更有识别度", "整体气质亲和正式"],
    tone: "calm",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "navy",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "skills", "experience", "awards"],
    sections: {
      hero: { variant: "stacked-profile-card" },
      education: { variant: "compact-rows" },
      experience: { variant: "role-first" },
      awards: { variant: "inline-list" },
      skills: { variant: "label-columns" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["skills", "experience", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "academic-ledger",
    name: "Academic Ledger",
    displayName: "学业履历版",
    description: "把教育、研究和奖项排得很清楚，适合学术信号较强的人。",
    familyId: "calm-academic",
    familyLabel: TEMPLATE_FAMILY_LABELS["calm-academic"],
    bestFor: "适合学术履历完整",
    fitSummary: "适合研究经历、课程项目、竞赛奖项都比较完整，想把履历整理得很清楚的人。",
    previewHighlights: ["教育识别度高", "奖项表格更清楚", "整体秩序感强"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "airy",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "ink",
      dividerStyle: "line",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "school-emphasis" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "two-column-table" },
      skills: { variant: "label-columns" },
    },
    compactionPolicy: {
      density: "airy",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "academic-signals",
    name: "Academic Signals",
    displayName: "成绩亮点版",
    description: "先把成绩、排名和保研信息拆开给人看，适合教育亮点明确的人。",
    familyId: "calm-academic",
    familyLabel: TEMPLATE_FAMILY_LABELS["calm-academic"],
    bestFor: "适合成绩排名突出",
    fitSummary: "适合教育亮点明确，想让 GPA、排名、保研和研究方向更容易被快速读到的人。",
    previewHighlights: ["教育亮点分块展示", "学术信号更集中", "正文阅读噪音更低"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "navy",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "skills", "experience", "awards"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "signal-grid" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "inline-list" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["awards", "skills", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "academic-timeline",
    name: "Academic Timeline",
    displayName: "阶段推进版",
    description: "先看时间推进和角色变化，适合研究、课题或项目线较长的人。",
    familyId: "calm-academic",
    familyLabel: TEMPLATE_FAMILY_LABELS["calm-academic"],
    bestFor: "适合研究项目较长",
    fitSummary: "适合有连续研究、课题或学术活动经历，想让时间推进关系更容易看懂的人。",
    previewHighlights: ["阶段变化更清楚", "页头更像履历页眉", "经历叙事更线性"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "ink",
      dividerStyle: "line",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "name-left-photo-right" },
      education: { variant: "highlight-strip" },
      experience: { variant: "role-first" },
      awards: { variant: "pill-row" },
      skills: { variant: "label-columns" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["experience", "awards", "skills"],
    },
  },
  {
    version: "v1",
    templateId: "academic-compact",
    name: "Academic Compact",
    displayName: "冷静压缩版",
    description: "把内容压得更紧，但还保持学术履历的秩序感。",
    familyId: "calm-academic",
    familyLabel: TEMPLATE_FAMILY_LABELS["calm-academic"],
    bestFor: "适合内容多但要冷静",
    fitSummary: "适合教育、研究、项目和技能都不少，需要一页内压紧信息但不显得慌乱的人。",
    previewHighlights: ["学业信号先集中", "信息密度更高", "模块切换更快"],
    tone: "academic",
    page: {
      size: "A4",
      marginPreset: "tight",
      layout: "single-column",
    },
    theme: {
      fontPair: "songti-sans",
      accentColor: "navy",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "experience", "skills", "awards"],
    sections: {
      hero: { variant: "split-meta-band" },
      education: { variant: "signal-grid" },
      experience: { variant: "compact-cards" },
      awards: { variant: "inline-list" },
      skills: { variant: "label-columns" },
    },
    compactionPolicy: {
      density: "tight",
      overflowPriority: ["skills", "awards", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "compact-elegance",
    name: "Compact Elegance",
    displayName: "一页紧凑版",
    description: "先把更多内容压进一页，适合经历和技能都偏多的人。",
    familyId: "modern-clean",
    familyLabel: TEMPLATE_FAMILY_LABELS["modern-clean"],
    bestFor: "适合内容多但想压一页",
    fitSummary: "适合经历和技能都偏多，需要在一页内提高版面利用率的人。",
    previewHighlights: ["信息密度更高", "经历卡片更利于快扫", "整体感受利落清爽"],
    tone: "modern",
    page: {
      size: "A4",
      marginPreset: "tight",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "forest",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "centered-name-minimal" },
      education: { variant: "compact-rows" },
      experience: { variant: "compact-cards" },
      awards: { variant: "inline-list" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "tight",
      overflowPriority: ["skills", "awards", "experience"],
    },
  },
  {
    version: "v1",
    templateId: "modern-balanced",
    name: "Modern Balanced",
    displayName: "清爽平衡版",
    description: "重点和留白更均衡，适合内容比较综合的人。",
    familyId: "modern-clean",
    familyLabel: TEMPLATE_FAMILY_LABELS["modern-clean"],
    bestFor: "适合内容比较均衡",
    fitSummary: "适合项目、实习、技能都比较平均，希望整体显得有条理、判断成本低的人。",
    previewHighlights: ["经历前置但不抢戏", "顶部信息更整齐", "模块关系更平衡"],
    tone: "modern",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "navy",
      dividerStyle: "line",
    },
    sectionOrder: ["experience", "education", "skills", "awards"],
    sections: {
      hero: { variant: "split-meta-band" },
      education: { variant: "highlight-strip" },
      experience: { variant: "role-first" },
      awards: { variant: "two-column-table" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["experience", "skills", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "modern-minimal",
    name: "Modern Minimal",
    displayName: "极简直给版",
    description: "减少装饰和说明，适合想让事实自己说话的人。",
    familyId: "modern-clean",
    familyLabel: TEMPLATE_FAMILY_LABELS["modern-clean"],
    bestFor: "适合信息已经很清楚",
    fitSummary: "适合信息已经很明确，想用更轻、更快的页面把重点直接交给读者的人。",
    previewHighlights: ["顶部更像名片块", "整体视觉更轻", "核心信息露出很直接"],
    tone: "modern",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "ink",
      dividerStyle: "soft",
    },
    sectionOrder: ["education", "skills", "experience", "awards"],
    sections: {
      hero: { variant: "stacked-profile-card" },
      education: { variant: "compact-rows" },
      experience: { variant: "stacked-bullets" },
      awards: { variant: "pill-row" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["skills", "experience", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "classic-banner",
    name: "Classic Banner",
    displayName: "上半页抢眼版",
    description: "先把页头和结果抬到上半页，适合想先抓住注意力的人。",
    familyId: "highlight-forward",
    familyLabel: TEMPLATE_FAMILY_LABELS["highlight-forward"],
    bestFor: "适合亮点和结果明确",
    fitSummary: "适合已经有明确成果点，想在前几秒就把卖点和结果传达出来的人。",
    previewHighlights: ["标题带更醒目", "结果导向感明显", "适合快节奏筛选"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "serif-sans",
      accentColor: "burgundy",
      dividerStyle: "bar",
    },
    sectionOrder: ["education", "experience", "awards", "skills"],
    sections: {
      hero: { variant: "classic-banner" },
      education: { variant: "highlight-strip" },
      experience: { variant: "metric-first" },
      awards: { variant: "two-column-table" },
      skills: { variant: "inline-tags" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["experience", "awards", "skills"],
    },
  },
  {
    version: "v1",
    templateId: "highlight-metrics",
    name: "Highlight Metrics",
    displayName: "数字结果优先",
    description: "先看量化结果和增长指标，适合成果点明确的人。",
    familyId: "highlight-forward",
    familyLabel: TEMPLATE_FAMILY_LABELS["highlight-forward"],
    bestFor: "适合数字结果很强",
    fitSummary: "适合有数字结果、增长指标或明确业务成效，想优先放大成果的人。",
    previewHighlights: ["结果摘要更直接", "数字信息更醒目", "阅读重点集中在经历模块"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "tight",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "forest",
      dividerStyle: "bar",
    },
    sectionOrder: ["experience", "education", "skills", "awards"],
    sections: {
      hero: { variant: "classic-banner" },
      education: { variant: "compact-rows" },
      experience: { variant: "result-callout" },
      awards: { variant: "pill-row" },
      skills: { variant: "grouped-chips" },
    },
    compactionPolicy: {
      density: "tight",
      overflowPriority: ["experience", "skills", "awards"],
    },
  },
  {
    version: "v1",
    templateId: "highlight-top-block",
    name: "Highlight Top Block",
    displayName: "技能卖点前置",
    description: "先看技能和个人卖点，适合筛选时会先看标签的岗位。",
    familyId: "highlight-forward",
    familyLabel: TEMPLATE_FAMILY_LABELS["highlight-forward"],
    bestFor: "适合技能标签先看",
    fitSummary: "适合技能筛选明显、想先展示核心标签与成果，再展开经历细节的人。",
    previewHighlights: ["上半页重点区更集中", "技能标签更先被看到", "亮点露出速度很快"],
    tone: "confident",
    page: {
      size: "A4",
      marginPreset: "balanced",
      layout: "single-column",
    },
    theme: {
      fontPair: "humanist-sans",
      accentColor: "navy",
      dividerStyle: "bar",
    },
    sectionOrder: ["skills", "experience", "education", "awards"],
    sections: {
      hero: { variant: "stacked-profile-card" },
      education: { variant: "compact-rows" },
      experience: { variant: "metric-first" },
      awards: { variant: "inline-list" },
      skills: { variant: "label-columns" },
    },
    compactionPolicy: {
      density: "balanced",
      overflowPriority: ["skills", "experience", "awards"],
    },
  },
];

export const assertUniqueTemplateIds = (
  manifests: readonly Pick<CuratedTemplateManifest, "templateId">[],
) => {
  const seenTemplateIds = new Set<string>();

  for (const manifest of manifests) {
    if (seenTemplateIds.has(manifest.templateId)) {
      throw new Error(`Duplicate templateId found in curated template library: ${manifest.templateId}`);
    }

    seenTemplateIds.add(manifest.templateId);
  }
};

assertUniqueTemplateIds(TEMPLATE_FAMILY_LIBRARY_DEFINITIONS);

export const TEMPLATE_FAMILY_LIBRARY = TEMPLATE_FAMILY_LIBRARY_DEFINITIONS;
